# Numpy-numerical python library

In [1]:
#input numpy library
import numpy as np

In [2]:
arr = np.array([[1,2,3,4],[2,5,6,7]])
arr

array([[1, 2, 3, 4],
       [2, 5, 6, 7]])

In [3]:
arr[0][2]

3

In [4]:
#dimension of array
print(arr.ndim)
print(arr.shape)
print(arr.data)
print(arr.size)
print(type(arr))

2
(2, 4)
8
<class 'numpy.ndarray'>


# LAB 1- Random Number Generator using numpy

In [5]:
from numpy import random
x= random.randint(100,size=3)
x

array([33, 69,  1])

In [6]:
y=random.rand(10)
y

array([0.86678322, 0.79450053, 0.23379399, 0.46354533, 0.29687742,
       0.47251782, 0.44085318, 0.1506841 , 0.62379205, 0.49905851])

In [7]:
z=random.random((2,3))
z

array([[0.2558076 , 0.61875272, 0.75664822],
       [0.14105804, 0.02292752, 0.64354266]])

In [8]:

x= random.randint(100,size=3)
random.seed(30)
x

array([79, 78, 71])

# numpy function

In [9]:
#zero matrix
zero=np.zeros((2,2))
zero

array([[0., 0.],
       [0., 0.]])

In [10]:
#one matrix/marrays
h=np.ones((3,3))
h

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#identity matrix
idt=np.eye((3))
idt

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#create constant matrix
cons=np.full((3,3),6)
cons

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

# array indexxing and slicing

In [13]:
arr = np.array([[1,2,3,4],[2,5,6,7],[3,6,8,9]])
arr

array([[1, 2, 3, 4],
       [2, 5, 6, 7],
       [3, 6, 8, 9]])

In [14]:
arr[0]

array([1, 2, 3, 4])

arr[0][0] a[0][1] a[0][2]

In [15]:
arr[0][1]=3
arr

array([[1, 3, 3, 4],
       [2, 5, 6, 7],
       [3, 6, 8, 9]])

In [16]:
#slicing
arr[1: ,1:3]

array([[5, 6],
       [6, 8]])

In [17]:
arr1=np.full((3,4),2)
arr1

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

# array brodcasting

In [18]:
print(arr,'\n\n',arr1)


[[1 3 3 4]
 [2 5 6 7]
 [3 6 8 9]] 

 [[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [19]:
#addition
print(arr1+arr)
print(np.add(arr1,arr))


[[ 3  5  5  6]
 [ 4  7  8  9]
 [ 5  8 10 11]]
[[ 3  5  5  6]
 [ 4  7  8  9]
 [ 5  8 10 11]]


In [20]:
#subtraction
print(np.subtract(arr1,arr))



[[ 1 -1 -1 -2]
 [ 0 -3 -4 -5]
 [-1 -4 -6 -7]]


In [21]:
#squar root
a=np.sqrt(arr1)
a

array([[1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356]])

In [22]:
np.sum(a)


16.970562748477143

In [23]:
b=np.sqrt(arr)
b

array([[1.        , 1.73205081, 1.73205081, 2.        ],
       [1.41421356, 2.23606798, 2.44948974, 2.64575131],
       [1.73205081, 2.44948974, 2.82842712, 3.        ]])

In [24]:
np.sum(b)

25.219591883956657

# calculate bmi of players

In [25]:
#height of player in inch
height_in=[9,8,7,4,5,6,11,12,13,15,8]
ht_np=np.array(height_in)
ht_np

array([ 9,  8,  7,  4,  5,  6, 11, 12, 13, 15,  8])

In [26]:
#inch to meter
ht_np=ht_np*0.0225
ht_np

array([0.2025, 0.18  , 0.1575, 0.09  , 0.1125, 0.135 , 0.2475, 0.27  ,
       0.2925, 0.3375, 0.18  ])

In [27]:
#weight of the players
weight_pd=[90,80,76,44,56,64,11,12,13,15,81]
wt_pd=np.array(weight_pd)
#convert ionto kg
wt_pd=wt_pd*0.45
wt_pd

array([40.5 , 36.  , 34.2 , 19.8 , 25.2 , 28.8 ,  4.95,  5.4 ,  5.85,
        6.75, 36.45])

In [28]:
#calculate bmi value
bmi=wt_pd/ht_np**2
bmi

array([ 987.65432099, 1111.11111111, 1378.68480726, 2444.44444444,
       1991.11111111, 1580.24691358,   80.80808081,   74.07407407,
         68.37606838,   59.25925926, 1125.        ])

In [29]:
bmi[bmi<1000]

array([987.65432099,  80.80808081,  74.07407407,  68.37606838,
        59.25925926])

In [30]:
players=np.array([wt_pd,ht_np])
players

array([[40.5   , 36.    , 34.2   , 19.8   , 25.2   , 28.8   ,  4.95  ,
         5.4   ,  5.85  ,  6.75  , 36.45  ],
       [ 0.2025,  0.18  ,  0.1575,  0.09  ,  0.1125,  0.135 ,  0.2475,
         0.27  ,  0.2925,  0.3375,  0.18  ]])

In [31]:
pT=players.T
pT.shape

(11, 2)

# statstical  operation

In [36]:
#min,max,mean,medion,std,var,perc,corrcoef

In [35]:
print(np.amax(wt_pd))
print(np.amax(ht_np))
print(np.corrcoef(wt_pd,ht_np))

40.5
0.33749999999999997
[[ 1.         -0.63768955]
 [-0.63768955  1.        ]]


In [38]:
#boolean
bools=[False,True,False,True,False]
bools

[False, True, False, True, False]

In [39]:
b=np.array(bools)
b


array([False,  True, False,  True, False])

In [40]:
b.sum()

2

In [41]:
b.any()

True

In [44]:
n=np.array(['a','a','a','b','b'])
n
            

array(['a', 'a', 'a', 'b', 'b'], dtype='<U1')

In [45]:
np.unique(n)

array(['a', 'b'], dtype='<U1')